#!/usr/bin/env python2
#
#  Copyright 2013 Science & Technology Facilities Council
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

import subprocess
import re
from datetime import datetime

re_snap = re.compile(r'^data/mirrors@(?P<date>[0-9]{4}-[0-9]{2}-[0-9]{2})$')

snapshots = subprocess.Popen(['/sbin/zfs', 'list', '-Hp', '-t', 'snapshot', '-o', 'name', '-s', 'name'], stdout=subprocess.PIPE).communicate()[0].splitlines()

count = 0

for snapshot in snapshots:
    m = re_snap.match(snapshot)
    if m:
        snap_date = m.group('date')
        snap_date = datetime.strptime(snap_date, '%Y-%m-%d')
        if (datetime.now() - snap_date).days > 365:
            print 'INFO: Removing snapshot %s' % snapshot
            print subprocess.Popen(['/sbin/zfs', 'destroy', snapshot], stdout=subprocess.PIPE).communicate()[0]
            count += 1

if count:
    print "INFO: Removed %d snapshots" % count
else:
    print "INFO: No snapshots needed removing"
